Repository kubernetes-client/ruby, pull requests merged in 2019-03, with the labels that each got.

#33 Add travis
  .travis-ci.yml
  .travis.yml
  kubernetes/Gemfile.lock
Labels: approved, cncf-cla: yes, lgtm, size/M

#34 Delete duplicate file
  .travis-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Move hand-written codes into separate folder from auto-generated codes
  kubernetes/kubernetes.gemspec
  kubernetes/src/kubernetes/config/error.rb
  kubernetes/src/kubernetes/config/incluster_config.rb
  kubernetes/src/kubernetes/config/kube_config.rb
  kubernetes/src/kubernetes/utils.rb
Labels: approved, cncf-cla: yes, lgtm, size/XS

#36 Improve default loading.
  examples/namespace/namespace.rb
  examples/simple/simple.rb
  kubernetes/spec/config/kube_config_spec.rb
  kubernetes/spec/fixtures/files/config/.kube/config
  kubernetes/spec/fixtures/files/config/config_2
  kubernetes/spec/helpers/file_fixtures.rb
  kubernetes/src/kubernetes/config/incluster_config.rb
  kubernetes/src/kubernetes/config/kube_config.rb
  kubernetes/src/kubernetes/loader.rb
Labels: approved, cncf-cla: yes, lgtm, size/L

#38 Add style linting with rubocop
  .travis.yml
  kubernetes/Gemfile
  kubernetes/Gemfile.lock
  kubernetes/spec/config/kube_config_spec.rb
  kubernetes/spec/utils_spec.rb
  kubernetes/src/kubernetes/config/incluster_config.rb
  kubernetes/src/kubernetes/config/kube_config.rb
  kubernetes/src/kubernetes/loader.rb
  kubernetes/src/kubernetes/utils.rb
Labels: approved, cncf-cla: yes, lgtm, size/L
