Repository kubernetes-client/ruby, pull requests merged in 2019-02, with the labels that each got.

#22 Add entry license topic on readme file
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#25 Add a simple example.
  README.md
  examples/simple/simple.rb
Labels: approved, cncf-cla: yes, lgtm, size/S

#28 Add drubin to reviewers list
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#30 Fix unit tests.
  kubernetes/spec/config/incluster_config_spec.rb
  kubernetes/spec/config/kube_config_spec.rb
  kubernetes/spec/fixtures/config/kube_config_hash.rb
  kubernetes/spec/helpers/file_fixtures.rb
  kubernetes/spec/utils_spec.rb
Labels: approved, cncf-cla: yes, lgtm, size/M

#11 Changed getting started install doc to use pre alpha.
  kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
