Repository kubernetes-client/ruby, pull requests merged in 2019-04, with the labels that each got.

#41 Add lint fixes for unit tests, and add lint testing of unit tests to CI
  .travis.yml
  kubernetes/spec/config/incluster_config_spec.rb
  kubernetes/spec/config/kube_config_spec.rb
  kubernetes/spec/config/matchers.rb
  kubernetes/spec/fixtures/config/kube_config_hash.rb
  kubernetes/spec/helpers/file_fixtures.rb
  kubernetes/spec/spec_helper.rb
  kubernetes/spec/utils_spec.rb
Labels: approved, cncf-cla: yes, lgtm, size/XL

#42 Fix issues with certificate based auth
  kubernetes/spec/utils_spec.rb
  kubernetes/src/kubernetes/config/kube_config.rb
  kubernetes/src/kubernetes/utils.rb
Labels: approved, cncf-cla: yes, lgtm, size/S

#39 Add support for Azure AAD login. Fix some bugs.
  kubernetes/lib/kubernetes.rb
  kubernetes/spec/config/kube_config_spec.rb
  kubernetes/spec/fixtures/config/kube_config_hash.rb
  kubernetes/src/kubernetes/config/kube_config.rb
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 Rename the package and update docs in preparation for publishing to rubygems.
  kubernetes/Gemfile.lock
  kubernetes/README.md
  kubernetes/kubernetes.gemspec
Labels: approved, cncf-cla: yes, lgtm, size/S
